# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20151215_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
